name       : perl-test-file-sharedir
version    : 1.001002
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/K/KE/KENTNL/Test-File-ShareDir-1.001002.tar.gz : b33647cbb4b2f2fcfbde4f8bb4383d0ac95c2f89c4c5770eb691f1643a337aad
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::File::ShareDir
description: |
    "Test::File::ShareDir" is some low level plumbing to enable a distribution to perform tests while consuming its own "share" directories in a manner similar to how they will be once installed.
builddeps  :
    - perl-test-fatal
    - perl-class-tiny
    - perl-file-copy-recursive
    - perl-file-sharedir
    - perl-path-tiny
    - perl-scope-guard
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
